name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Instalar herramientas de sistema
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget
        pip3 install --upgrade pip
        pip3 install buildozer Cython

    - name: Aceptar licencias Android SDK
      run: |
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg
        yes | buildozer android accept_license || true

    - name: Inicializar Buildozer
      run: buildozer init || true

    - name: Instalar manualmente build-tools 33
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" "build-tools;33.0.0" "platforms;android-33" \
          --sdk_root=$HOME/.buildozer/android/platform/android-sdk || true

    - name: Validar buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "Falta buildozer.spec" && exit 1
        fi

    - name: Compilar APK
      run: buildozer android debug

    - name: Subir artefacto APK
      uses: actions/upload-artifact@v3
      with:
        name: APK-MiAppEjemplo
        path: bin/*.apk
