name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk libffi-dev libssl-dev python3-dev libjpeg-dev zlib1g-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Manually install Android SDK & accept licenses
      run: |
        mkdir -p $HOME/.android
        echo "### Creating SDK folder"
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip
        mkdir cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      env:
        ANDROIDSDK: $HOME/android-sdk
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export PATH=$ANDROIDSDK/cmdline-tools/latest/bin:$ANDROIDSDK/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AviatorPredictor-APK
        path: bin/*.apk
