name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias de sistema
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget
        pip3 install --upgrade pip
        pip3 install buildozer Cython

    - name: Crear archivo de licencias y aceptar automáticamente
      run: |
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg
        yes | buildozer android accept_license

    - name: Inicializar buildozer.spec si no existe
      run: buildozer init || true

    - name: Instalar build-tools 36.0.0 (forzar)
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0" "platform-tools" --sdk_root=$HOME/.buildozer/android/platform/android-sdk

    - name: Validar archivo buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "Falta buildozer.spec" && exit 1
        fi

    - name: Compilar APK
      run: buildozer android debug

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: APK-Aviator
        path: bin/*.apk
