name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USE_LOCAL_ANT: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk libgl1-mesa-dev libncurses5 curl
          python3 -m pip install --upgrade pip
          pip install --user buildozer cython==0.29.36

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/ant/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdtools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"

      - name: Install Apache ANT manually
        run: |
          curl -O https://downloads.apache.org/ant/binaries/apache-ant-1.10.14-bin.zip
          unzip -q apache-ant-1.10.14-bin.zip
          mv apache-ant-1.10.14 $HOME/ant

      - name: Force local ANT usage
        run: |
          mkdir -p ~/.buildozer
          echo "[buildozer]" > ~/.buildozer/global.ini
          echo "apache_ant_path = $HOME/ant" >> ~/.buildozer/global.ini

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AviatorPredictor-APK
          path: bin/*.apk
