name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk git libgl1-mesa-dev libncurses5 wget

    - name: Install Apache ANT manually
      run: |
        wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
        tar -xzf apache-ant-1.9.4-bin.tar.gz
        mv apache-ant-1.9.4 $HOME/ant
        echo "$HOME/ant/bin" >> $GITHUB_PATH

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK Command-line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH

    - name: Accept licenses and install build tools
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        buildozer android debug --verbose

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: AviatorPredictor
        path: bin/*.apk
