name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user buildozer cython

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

    - name: Install Android SDK & NDK manually
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-*.zip -d latest
        rm commandlinetools-linux-*.zip
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

    - name: Install other Python requirements
      run: |
        pip install --user appdirs colorama jinja2 sh 'build' toml packaging setuptools

    - name: Install Git & Cython
      run: |
        sudo apt update
        sudo apt install -y git cython

    - name: Build APK with Buildozer
      run: |
        buildozer android debug
