name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk wget libncurses5 python3-pip python3-setuptools

      - name: Install pip dependencies (incluye Cython)
        run: |
          python3 -m pip install --upgrade pip
          pip install Cython
          pip install buildozer

      - name: Prepare environment
        run: |
          mkdir -p ~/.buildozer/android/platform
          mkdir -p ~/android-sdk

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Run Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AviatorPredictor-APK
          path: bin/*.apk
