name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          export ANDROIDSDK=$HOME/android-sdk
          export PATH=$PATH:$ANDROIDSDK/tools/bin
          buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AviatorPredictor-APK
          path: ./bin/*.apk
